# Generated by Django 6.0.2 on 2026-02-07 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0002_menuitemaddondefinition_inventoryreport_taxonomyterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mape', models.FloatField(blank=True, help_text='Mean Absolute Percentage Error (lower is better)', null=True)),
                ('rmse', models.FloatField(blank=True, help_text='Root Mean Squared Error', null=True)),
                ('mae', models.FloatField(blank=True, help_text='Mean Absolute Error', null=True)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('training_start_date', models.DateField(help_text='Start of training data range')),
                ('training_end_date', models.DateField(help_text='End of training data range')),
                ('data_points_used', models.IntegerField(default=0, help_text='Number of data points used in training')),
                ('model_params', models.JSONField(blank=True, default=dict, help_text='Prophet model parameters used during training')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is currently in use for predictions')),
                ('item', models.ForeignKey(blank=True, help_text='Optional - specific item this model forecasts. Null means place-level model.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_models', to='inventory.item')),
                ('place', models.ForeignKey(help_text='The place/location this model was trained for', on_delete=django.db.models.deletion.CASCADE, related_name='forecast_models', to='core.place')),
            ],
            options={
                'verbose_name': 'Forecast Model',
                'verbose_name_plural': 'Forecast Models',
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(help_text='The date being forecasted')),
                ('predicted_quantity', models.FloatField(help_text='Predicted demand quantity')),
                ('lower_bound_80', models.FloatField(blank=True, help_text='Lower bound of 80% confidence interval', null=True)),
                ('upper_bound_80', models.FloatField(blank=True, help_text='Upper bound of 80% confidence interval', null=True)),
                ('lower_bound_95', models.FloatField(blank=True, help_text='Lower bound of 95% confidence interval', null=True)),
                ('upper_bound_95', models.FloatField(blank=True, help_text='Upper bound of 95% confidence interval', null=True)),
                ('trend', models.FloatField(blank=True, help_text='Trend component from Prophet', null=True)),
                ('weekly_seasonality', models.FloatField(blank=True, help_text='Weekly seasonality component', null=True)),
                ('yearly_seasonality', models.FloatField(blank=True, help_text='Yearly seasonality component', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='inventory.item')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='core.place')),
                ('forecast_model', models.ForeignKey(help_text='The model that generated this forecast', on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='intelligence.forecastmodel')),
            ],
            options={
                'verbose_name': 'Demand Forecast',
                'verbose_name_plural': 'Demand Forecasts',
                'ordering': ['forecast_date'],
                'unique_together': {('forecast_model', 'place', 'item', 'forecast_date')},
            },
        ),
    ]
